# Generated by Django 3.2.4 on 2021-06-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('alternative_phone', models.CharField(max_length=15)),
                ('second_chamber', models.CharField(blank=True, max_length=100, null=True)),
                ('third_chamber', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address', models.TextField()),
                ('parmanent_address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='doctor_photo/')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.designation')),
            ],
        ),
    ]
